# Generated by Django 4.2.11 on 2026-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_order_transport_order_warehouse_stockentry_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivered_at_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
